export enum EmMlApiErrorCode {
  GENERAL = 0,
  PROT_RESP_STATUS_CODE = 1,
  PROT_RESP_MALFORMAT_DATA = 2,
  PROT_RESP_NO_RESP = 3,
  PROT_REQ_NOT_SENT = 4,
  MALFORMAT_DATA = 5,
  SERVER_ERROR = 6,
}
